services:
  php-env:
    build:
      context: .  
      dockerfile: ./php/Dockerfile 
    volumes:
      - ../htdocs:/var/www/html
      - ./php/config.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./php/config.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
    extra_hosts:
      #Ensure that the host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway
    ports:
      - 9000:80
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50MiB
    depends_on:
      - mysql_db
  mysql_db:
    image: mysql:latest
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 400MiB
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 9001:80
    environment:
      PMA_HOST: mysql_db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 100MiB
    depends_on:
      - mysql_db
volumes:
    mysqldata: